import { colors } from 'variables';

const portfolios = {
  "CaseStudy": {
    title: "Case Study",
    desc: 'We created our own virtual headquarters using the logo symbol of the agency, we converted it into a stunning high-end architectural visual. Our plan is to convert this image into a 360 virtual walkthrough for our audience where they can integrate and explore the 3D environment.',
    detailTitle: 'The Virtual Space',
    detailDesc: 'The images below are the renders for different areas inside the headquarters. These case studies help us build the environment using Forest Pack plugins in 3DS max, lighting with Vray Hotfix.',
    image: {
      src: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/ttfd_Scene-A_Homepage Cover_2080x1440.jpg`,
      width: 2560,
      height: 1440,
    },
    visibleOnHomepage: true,
    bgColor: colors.orange,
    gridItems: [
      {
        itemId: 1,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/01_ttfd_Scene-A_2080x1440.jpg`,
        layout: { x: 0, y: 0, w: 6, h: 1 },
        smLayout: { x: 0, y: 0, w: 12, h: 1 },
      },
      {
        itemId: 2,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/02_Scene to 2nd Lvl_Vertical_2080x2880.jpg`,
        smImage: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/02_Scene to 2nd Lvl_Landscape_2080x1440.jpg`,
        maxHeightSource: [1, 3],
        layout: { x: 6, y: 0, w: 6, h: 2 },
        smLayout: { x: 0, y: 1, w: 12, h: 1 },
      },
      {
        itemId: 3,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/03_Scene-C1_A_2080x1440.jpg`,
        width: 2560,
        height: 1440,
        layout: { x: 0, y: 1, w:6, h: 1 },
        smLayout: { x: 0, y: 2, w: 12, h: 1 },
      },
      {
        itemId: 4,
        text: `An environment with virtual tour function for audience to experience the actual space and proportion.`,
        bgColor: "turquoise",
        color: "white",
        layout: { x: 6, y: 2, w: 12, h: 1 },
        smLayout: { x: 0, y: 3, w: 12, h: 1 },
      },
      {
        itemId: 5,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/04_Scene C1_B_1040x720.jpg`,
        layout: { x: 0, y: 3, w: 6, h: 1 },
        smLayout: { x: 0, y: 4, w: 12, h: 1 },
      },
      {
        itemId: 6,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/05_Scene C1_C_1040x720.jpg`,
        layout: { x: 6, y: 3, w: 6, h: 1 },
        smLayout: { x: 0, y: 5, w: 12, h: 1 },
      },
      {
        itemId: 7,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/06_Scene-C3_A_1040x720.jpg`,
        layout: { x: 0, y: 4, w: 6, h: 1 },
        smLayout: { x: 0, y: 4, w: 12, h: 1 },
      },
      {
        itemId: 8,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/07_Scene-C4_A_1040x720.jpg`,
        layout: { x: 6, y: 4, w: 6, h: 1 },
        smLayout: { x: 0, y: 5, w: 12, h: 1 },
      },
      {
        itemId: 9,
        text: `2nd-Storey area and collaboration space concept in a twisted, flowing shape concept. `,
        bgColor: "turquoise",
        color: "white",
        layout: { x: 0, y: 5, w: 12, h: 1 },
        smLayout: { x: 0, y: 6, w: 12, h: 1 },
      },
      {
        itemId: 10,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/08_Scene-C5_A_Vertical_2080x2880.jpg`,
        smImage: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/08_Scene-C5_A_Landscape_2080x2880.jpg`,
        maxHeightSource: [11, 12],
        layout: { x: 0, y: 6, w: 6, h: 2 },
        smLayout: { x: 0, y: 7, w: 12, h: 1 },
      },
      {
        itemId: 11,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/09_Scene-C6_A_1040x720.jpg`,
        layout: { x: 6, y: 6, w:6, h: 1 },
        smLayout: { x: 0, y: 8, w: 12, h: 1 },
      },
      {
        itemId: 12,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/10_Scene-C6_D_1040x720.jpg`,
        layout: { x: 6, y: 7, w:6, h: 1 },
        smLayout: { x: 0, y: 9, w: 12, h: 1 },
      },
      {
        itemId: 13,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/11_Scene-C6_C_1040x720.jpg`,
        width: 2560,
        height: 1440,
        layout: { x: 0, y: 8, w: 6, h: 1 },
        smLayout: { x: 0, y: 10, w: 12, h: 1 },
      },
      {
        itemId: 14,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/thetwentyfourdots/12_Scene-C6_B_1040x720.jpg`,
        width: 2560,
        height: 1440,
        layout: { x: 6, y: 8, w: 6, h: 1 },
        smLayout: { x: 0, y: 11, w: 12, h: 1 },
      },
      {
        itemId: 15,
        text: `Glass installation access to the lounge area with a featured wall in the entrance and exit.`,
        bgColor: "turquoise",
        color: "white",
        layout: { x: 0, y: 12, w: 12, h: 1 },
        smLayout: { x: 0, y: 12, w: 12, h: 1 },
      },
    ],
  },
  "SunflowerLoft": {
    title: 'Sunflower Loft',
    desc: 'A proposal for school room renovation to create and divide a small room into 2 types where students can collaborate and relax after school hours. ' +
      'Applying vibrant colours with a cozy look and feel will give them a sense of relaxation to do more and be active in developing their skills.', 
    detailDesc: 'An interior design with lively colour furniture complimented students for uplifting their creativity and passion for research and study.',
    image: {
      src: `${process.env.PUBLIC_URL}/assets/images/portfolio/CHIJ ID/CHIJ_Homepage Cover_Lounge A1_2080x1440.jpg`,
      width: 2080,
      height: 1440,
    },
    visibleOnHomepage: true,
    bgColor: colors.yellow,
    gridItems: [
      {
        itemId: 1,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/CHIJ ID/01_3D key Plan_2080x1440.jpg`,
        layout: { x: 0, y: 0, w: 6, h: 1 },
        smLayout: { x: 0, y: 0, w: 12, h: 1 },
      },
      {
        itemId: 2,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/CHIJ ID/02_entrance open_Vertical_2080x2880.jpg`,
        smImage: `${process.env.PUBLIC_URL}/assets/images/portfolio/CHIJ ID/02_entrance open_Landscape_2080x1440.jpg`,
        maxHeightSource: [1, 3],
        layout: { x: 6, y: 0, w: 6, h: 2 },
        smLayout: { x: 0, y: 1, w: 12, h: 1 },
      },
      {
        itemId: 3,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/CHIJ ID/03_Lego wall_2080x1440.jpg`,
        layout: { x: 0, y: 1, w:6, h: 1 },
        smLayout: { x: 0, y: 2, w: 12, h: 1 },
      },
      {
        itemId: 4,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/CHIJ ID/04_Lounge A2_2080x1440.jpg`,
        layout: { x: 0, y: 2, w: 6, h: 1 },
        smLayout: { x: 0, y: 3, w: 12, h: 1 },
      },
      {
        itemId: 5,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/CHIJ ID/05_Lounge A1_2080x1440.jpg`,
        layout: { x: 6, y: 2, w: 6, h: 1 },
        smLayout: { x: 0, y: 4, w: 12, h: 1 },
      },
      {
        itemId: 6,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/CHIJ ID/06_Lounge A3_2080x1440.jpg`,
        width: 2560,
        height: 1440,
        layout: { x: 0, y: 3, w: 6, h: 1 },
        smLayout: { x: 0, y: 5, w: 12, h: 1 },
      },
      {
        itemId: 7,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/CHIJ ID/07_Lounge B3_2080x1440.jpg`,
        layout: { x: 6, y: 3, w: 6, h: 1 },
        smLayout: { x: 0, y: 6, w: 12, h: 1 },
      },
      {
        itemId: 8,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/CHIJ ID/08_Lounge B1_2080x1440.jpg`,
        layout: { x: 0, y: 4, w: 6, h: 1 },
        smLayout: { x: 0, y: 7, w: 12, h: 1 },
      },
      {
        itemId: 9,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/CHIJ ID/09_Lounge B2_2080x1440.jpg`,
        layout: { x: 6, y: 4, w: 6, h: 1 },
        smLayout: { x: 0, y: 8, w: 12, h: 1 },
      },
      {
        itemId: 10,
        text: 'Having fun while learning is always a great practice when developing your skills and creativity.',
        bgColor: "turquoise",
        color: "white",
        layout: { x: 0, y: 5, w: 12, h: 1 },
        smLayout: { x: 0, y: 9, w: 12, h: 1 },
      },
    ],
  },
  "CloverResort": {
    title: 'Clover Resort',
    desc: 'Concept proposal for an architectural firm where we develop a concept from a cloverleaf and translate it to a high-quality image render for visual representation.', 
    image: {
      src: `${process.env.PUBLIC_URL}/assets/images/portfolio/Clover Resort/C-1.3_2080x1440.jpg`,
      width: 3000,
      height: 2000,
    },
    visibleOnHomepage: true,
    bgColor: colors.turquoise,
    gridItems: [
      {
        itemId: 1,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/Clover Resort/01_C-1.2_2080x1440.jpg`,
        layout: { x: 0, y: 0, w: 6, h: 1 },
        smLayout: { x: 0, y: 0, w: 12, h: 1 },
      },
      {
        itemId: 2,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/Clover Resort/02_C-1.1_2080x1440.jpg`,
        layout: { x: 6, y: 0, w: 6, h: 1 },
        smLayout: { x: 0, y: 1, w: 12, h: 1 },
      },
      {
        itemId: 3,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/Clover Resort/03_C-1.4_2080x1440.jpg`,
        layout: { x: 0, y: 1, w:6, h: 1 },
        smLayout: { x: 0, y: 2, w: 12, h: 1 },
      },
      {
        itemId: 4,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/Clover Resort/04_C-1.3_2080x1440.jpg`,
        layout: { x: 6, y: 1, w: 6, h: 1 },
        smLayout: { x: 0, y: 3, w: 12, h: 1 },
      },
    ],
  },
  "Residential": {
    title: "Residential",
    desc: 'Our team created a minimalist interior residential settings for living room dining and kitchen.', 
    image: {
      src: `${process.env.PUBLIC_URL}/assets/images/portfolio/Residential/Residential_Homepage Cover_2080x1440.jpg`,
      width: 1000,
      height: 624,
    },
    visibleOnHomepage: true,
    bgColor: colors.cyan,
    gridItems: [
      {
        itemId: 1,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/Residential/01_A-Dining-Area_2080x2880.jpg`,
        width: 2560,
        height: 1440,
        layout: { x: 0, y: 0, w: 6, h: 1 },
        smLayout: { x: 0, y: 0, w: 12, h: 1 },
      },
      {
        itemId: 2,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/Residential/02_A-Kitchen-Area0_2080x2880.jpg`,
        width: 900,
        height: 1440,
        layout: { x: 6, y: 0, w: 6, h: 1 },
        smLayout: { x: 0, y: 1, w: 12, h: 1 },
      }, 
    ],
  },
  "HPFixtures": {
    title: "HP Product Display",
    desc: "Developing a table fixtures for cartridges and other HP items", 
    image: {
      src: `${process.env.PUBLIC_URL}/assets/images/portfolio/HP Fixtures/1. HP_Counter Top_1_2080x1440.jpg`,
      width: 3000,
      height: 2000,
    },
    bgColor: colors.turquoise,
    gridItems: [
      {
        itemId: 1,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/HP Fixtures/1. HP_Counter Top_1_2080x1440.jpg`,
        layout: { x: 0, y: 0, w: 6, h: 1 },
        smLayout: { x: 0, y: 0, w: 12, h: 1 },
      },
      {
        itemId: 2,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/HP Fixtures/2. HP_Counter Top_2_2080x1440.jpg`,
        layout: { x: 6, y: 0, w: 6, h: 1 },
        smLayout: { x: 0, y: 1, w: 12, h: 1 },
      },
      {
        itemId: 3,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/HP Fixtures/3. HP Counter Top_2080x1440.jpg`,
        layout: { x: 0, y: 1, w:6, h: 1 },
        smLayout: { x: 0, y: 2, w: 12, h: 1 },
      },
      {
        itemId: 4,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/HP Fixtures/4. HP Counter Top_2080x1440.jpg`,
        layout: { x: 6, y: 1, w: 6, h: 1 },
        smLayout: { x: 0, y: 3, w: 12, h: 1 },
      },
      {
        itemId: 5,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/HP Fixtures/5. Wallbay_2080x2880.jpg`,
        layout: { x: 0, y: 2, w:6, h: 1 },
        smLayout: { x: 0, y: 4, w: 12, h: 1 },
      },
      {
        itemId: 6,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/HP Fixtures/6. Endcap_2080x2880.jpg`,
        layout: { x: 6, y: 2, w: 6, h: 1 },
        smLayout: { x: 0, y: 5, w: 12, h: 1 },
      },
    ],
  },
  "SKII": {
    title: "SKII",
    desc: "We helped our client to establish 3D assets and images to use in there virtual platform for SKII product display", 
    bgColor: colors.turquoise,
    gridItems: [
      {
        itemId: 1,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/1. CN Global Counter Angle 1_2080x1440.jpg`,
        layout: { x: 0, y: 0, w: 6, h: 1 },
        smLayout: { x: 0, y: 0, w: 12, h: 1 },
      },
      {
        itemId: 2,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/2. CN Global Counter Angle 2_2080x1440.jpg`,
        layout: { x: 6, y: 0, w: 6, h: 1 },
        smLayout: { x: 0, y: 1, w: 12, h: 1 },
      },
      {
        itemId: 3,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/3. SKII_No2_Counter_R4_2080x1440.jpg`,
        layout: { x: 0, y: 1, w:6, h: 1 },
        smLayout: { x: 0, y: 2, w: 12, h: 1 },
      },
      {
        itemId: 4,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/4. SKII_No2_Counter_R4.2_2080x1440.jpg`,
        layout: { x: 6, y: 1, w: 6, h: 1 },
        smLayout: { x: 0, y: 3, w: 12, h: 1 },
      },
      {
        itemId: 5,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/5. SKII_No5_Counter_R1_Front Perspective_2080x1440.jpg`,
        layout: { x: 0, y: 2, w:6, h: 1 },
        smLayout: { x: 0, y: 4, w: 12, h: 1 },
      },
      {
        itemId: 6,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/6. SKII_No6_JP Keio Shinjuku_A_2080x1440.jpg`,
        layout: { x: 6, y: 2, w: 6, h: 1 },
        smLayout: { x: 0, y: 5, w: 12, h: 1 },
      },
      {
        itemId: 7,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/7. SKII Retail Booth_2080x1440.jpg`,
        layout: { x: 0, y: 3, w:6, h: 1 },
        smLayout: { x: 0, y: 6, w: 12, h: 1 },
      },
      {
        itemId: 8,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/8. SKII_No8_Counter_R2 Perspective_2080x1440.jpg`,
        layout: { x: 6, y: 3, w: 6, h: 1 },
        smLayout: { x: 0, y: 7, w: 12, h: 1 },
      },
      {
        itemId: 9,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/9. SKII_No9_Counter_R1 Perspective1_2080x1440.jpg`,
        layout: { x: 0, y: 4, w:6, h: 1 },
        smLayout: { x: 0, y: 8, w: 12, h: 1 },
      },
      {
        itemId: 10,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/10. SKII_No9_Counter_R1 Perspective2_2080x1440.jpg`,
        layout: { x: 6, y: 4, w: 6, h: 1 },
        smLayout: { x: 0, y: 9, w: 12, h: 1 },
      },
      {
        itemId: 11,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/11. SKII_No10_Perspective1_2080x1440.jpg`,
        layout: { x: 0, y: 5, w:6, h: 1 },
        smLayout: { x: 0, y: 10, w: 12, h: 1 },
      },
      {
        itemId: 12,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/12. SKII_No10_Perspective3_2080x1440.jpg`,
        layout: { x: 6, y: 5, w: 6, h: 1 },
        smLayout: { x: 0, y: 11, w: 12, h: 1 },
      },
      {
        itemId: 13,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/13. SKII_No11_Counter_Aerial_R1_2080x1440.jpg`,
        layout: { x: 0, y: 6, w:6, h: 1 },
        smLayout: { x: 0, y: 12, w: 12, h: 1 },
      },
      {
        itemId: 14,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/14. SKII_No12_Counter_Render_1_2080x1440.jpg`,
        layout: { x: 6, y: 6, w: 6, h: 1 },
        smLayout: { x: 0, y: 13, w: 12, h: 1 },
      },
      {
        itemId: 15,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/15. SKII_No12_Counter_Render_2_2080x1440.jpg`,
        layout: { x: 0, y: 7, w:6, h: 1 },
        smLayout: { x: 0, y: 14, w: 12, h: 1 },
      },
      {
        itemId: 16,
        image: `${process.env.PUBLIC_URL}/assets/images/portfolio/SKII/16. SKII_No12_Counter_Render_3_2080x1440.jpg`,
        layout: { x: 6, y: 7, w: 6, h: 1 },
        smLayout: { x: 0, y: 15, w: 12, h: 1 },
      },
    ],
  },
};

export default portfolios;